# Generated by Django 3.2.8 on 2022-01-15 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('photo_link', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('photo_link', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('description', models.TextField(max_length=500)),
                ('photo_link', models.TextField(max_length=500)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('workoutPlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDayExerciseSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('workoutPlanDayExerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplandayexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('workoutPlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutplanday', to='workout.workoutplan')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='musclegroups',
            field=models.ManyToManyField(to='workout.MuscleGroup'),
        ),
    ]
