# Generated by Django 3.2.8 on 2021-12-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('WorkoutPlanId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay',
            fields=[
                ('WorkoutPlanDayId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('WorkoutPlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay_Exercise',
            fields=[
                ('WorkoutPlanDay_ExerciseId', models.IntegerField(primary_key=True, serialize=False)),
                ('ExerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('WorkoutPlanDayId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplanday')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanDay_Exercise_Sets',
            fields=[
                ('WorkoutPlanDay_Exercise_SetsId', models.IntegerField(primary_key=True, serialize=False)),
                ('reps', models.IntegerField()),
                ('WorkoutPlanDay_ExerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplanday_exercise')),
            ],
        ),
    ]
