# Generated by Django 3.2.8 on 2022-01-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplandayexercise',
            name='workoutPlanId',
        ),
        migrations.AddField(
            model_name='workoutplandayexercise',
            name='workoutPlanDayId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutplanday'),
            preserve_default=False,
        ),
    ]
