# Generated by Django 3.2.8 on 2022-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20220115_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplandayexercisesets',
            name='series',
            field=models.IntegerField(default=5),
        ),
    ]
