# Generated by Django 3.2.9 on 2021-11-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
