# Generated by Django 3.2.9 on 2021-11-21 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparameters',
            name='id',
        ),
        migrations.AlterField(
            model_name='userparameters',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
